version: '3.1'

services:
  jane-research:
    image: jane-research
    command: "sleep 1000h"
    volumes:
      - /home/ubuntu/jane:/root/jane
      - /data:/root/data
    secrets:  
      - aws_credentials
      - sql_credentials
      - prod_sql_credentials
      - prod_research_sql_credentials
      - prod_research_write_sql_credentials
    environment:
      - AWS_CREDENTIALS=/run/secrets/aws_credentials
      - SQL_CREDENTIALS=/run/secrets/sql_credentials
      - PROD_SQL_CREDENTIALS=/run/secrets/prod_sql_credentials
      - PROD_RESEARCH_SQL_CREDENTIALS=/run/secrets/prod_research_sql_credentials
      - PROD_RESEARCH_WRITE_SQL_CREDENTIALS=/run/secrets/prod_research_write_sql_credentials
    ports:
        - "8866:8866"
    logging:
      driver: journald
      options:
        tag: "jane-research"
    container_name:
      jane-research

secrets:
  aws_credentials:
    file: ./aws_credentials.json
  sql_credentials:
    file: ./sql_credentials.json
  prod_sql_credentials:
    file: ./prod_sql_credentials.json
  prod_research_sql_credentials:
    file: ./prod_research_sql_credentials.json
  prod_research_write_sql_credentials:
    file: ./prod_research_write_sql_credentials.json 
