version: '3.1'

services:
  alok_research:
    image: alok_research_image
    command: "sleep 1000h"
    volumes:
      - /home/ubuntu/alok:/root/alok
      - /data:/root/data
    secrets:  
      - aws_credentials
    environment:
      - AWS_CREDENTIALS=/run/secrets/aws_credentials
    ports:
      - "9999:9999"
    logging:
      driver: journald
      options:
        tag: "alok_research"
    container_name:
      alok_research

secrets:
  aws_credentials:
    file: ./aws_credentials.json
