version: '3.1'

services:
  alok-research:
    image: alok-research-image
    command: "sleep 1000h"
    volumes:
      - /home/ubuntu/alok:/root/alok
      - /data:/root/data
    secrets:  
      - aws_credentials
      - sql_credentials
      - prod_sql_credentials
      - prod_research_sql_credentials
      - prod_research_write_sql_credentials
      - data_warehouse_sql_credentials
    environment:
      - AWS_CREDENTIALS=/run/secrets/aws_credentials
      - SQL_CREDENTIALS=/run/secrets/sql_credentials
      - PROD_SQL_CREDENTIALS=/run/secrets/prod_sql_credentials
      - PROD_RESEARCH_SQL_CREDENTIALS=/run/secrets/prod_research_sql_credentials
      - PROD_RESEARCH_WRITE_SQL_CREDENTIALS=/run/secrets/prod_research_write_sql_credentials
      - DATA_WAREHOUSE_SQL_CREDENTIALS=/run/secrets/data_warehouse_sql_credentials
    ports:
      - "9999:9999"
    logging:
      driver: journald
      options:
        tag: "alok-research"
    container_name:
      alok-research

secrets:
  aws_credentials:
    file: ./aws_credentials.json
  sql_credentials:
    file: ./sql_credentials.json
  prod_sql_credentials:
    file: ./prod_sql_credentials.json
  prod_research_sql_credentials:
    file: ./prod_research_sql_credentials.json
  prod_research_write_sql_credentials:
    file: ./prod_research_write_sql_credentials.json
  data_warehouse_sql_credentials:
    file: ./data_warehouse_sql_credentials.json
