version: '3.1'
services:
  aquabyte-trainer:
    build: ../
    env_file:
      - ./special.env
    volumes:
      - /home/ubuntu/thomas:/root/thomas/
      - /data/:/root/data/
    ports:
      - "1234:1234"
    logging:
      driver: journald
      options:
        tag: "aquabyte-trainer"
    image: aquabyte-trainer
