version: '3.1'

services:
  calibration:
    command: sleep 1000h
    image: calibration
    volumes:
      - /Users/aloksaxena/Documents/aquabyteai/notebooks/calibration:/app
    ports:
      - "9999:9999"
    logging:
      # driver: journald
      options:
        tag: "calibration"
    container_name:
      calibration