version: '3.1'

services:
  alok_biomass:
    image: deeplearning
    volumes:
      - /home/ubuntu/alok:/root/alok
      - /data:/root/data
    ports:
      - "9999:9999"
    logging:
      driver: journald
      options:
        tag: "alok_biomass"
    container_name:
      alok_biomass